/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eksploator.ui;

import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jan
 */
public class dataPanel extends javax.swing.JPanel {

    // plik z danymi

    File file;

    /**
     * Creates new form dataPanel
     */
    public dataPanel(File file) {
        String line = null;
        rowData = new Vector();
        FileInputStream fin;
        float f;
        char c;
        int row = 0;
        int col = 0;
        try {
            fin = new FileInputStream(file);
            DataInputStream din = new DataInputStream(fin);
            do{
                Vector colDat = new Vector();
                col = 0;
                //do{
                    f = din.readFloat();
                    System.out.println("Wczytano:" + f +"\tkol: " +col + "\twier: " +row);
                    colDat.add(f);
                    
                    col++;
               // }while(c != '\n');
                rowData.add(colDat);
                row++;
            }while(din.available()>0);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(dataPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
                Logger.getLogger(dataPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        

        

        initComponents();
        this.setName(file.getName());

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout());

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            rowData,
            colNames
        ));
        jScrollPane1.setViewportView(dataTable);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void finalize() throws Throwable {
        super.finalize();
        System.out.println("close");
    }

    Vector rowData ;
    Vector colNames;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
